// Public product names from the sanitized 2026-09-22 regional feasibility probe.
export const proteinNames = [
  "Amul High Protein Wheat Flour, 65 g | Pack of 30 Sachets",
  "Amul Kool Protein Milkshake | Chocolate, 180 mL | Pack of 8",
  "Amul Kool Protein Milkshake | Chocolate, 180 mL | Pack of 30",
  "Amul Kool Protein Milkshake | Kesar, 180 mL | Pack of 8",
  "Amul Kool Protein Milkshake | Kesar, 180 mL | Pack of 30",
  "Amul Kool Protein Milkshake | Arabica Coffee, 180 mL | Pack of 8",
  "Amul Kool Protein Milkshake | Arabica Coffee, 180 mL | Pack of 30",
  "Amul Kool Protein Milkshake | Vanilla, 180 mL | Pack of 8",
  "Amul Kool Protein Milkshake | Vanilla, 180 mL | Pack of 30",
  "Amul High Protein Blueberry Shake, 200 mL | Pack of 30",
  "Amul High Protein Paneer, 400 g | Pack of 2",
  "Amul High Protein Paneer, 400 g | Pack of 24",
  "Amul High Protein Buttermilk, 200 mL | Pack of 30",
  "Amul Whey Protein Gift Pack, 32 g | Pack of 10 sachets",
  "Amul Whey Protein, 32 g | Pack of 30 Sachets",
  "Amul Whey Protein, 32 g | Pack of 60 Sachets",
  "Amul Chocolate Whey Protein Gift Pack, 34 g | Pack of 10 sachets",
  "Amul Chocolate Whey Protein, 34 g | Pack of 30 sachets",
  "Amul Chocolate Whey Protein, 34 g | Pack of 60 sachets",
  "Amul High Protein Plain Lassi, 200 mL | Pack of 30",
  "Amul High Protein Rose Lassi, 200 mL | Pack of 30",
  "Amul High Protein Milk, 250 mL | Pack of 8",
  "Amul High Protein Milk, 250 mL | Pack of 32",
];
